
# PART1: Directory for downloading .fasta and .gtf files and preparing genome index
# PART2: RSEM parameters
# PART3: sample list

# 1. Directory for downloading .fasta and .gtf files and preparing genome index
# modify the path to your genome folder
downloadDir: '/data/local/d01/PROOF/genomes/GRCh38/'

# 2. RSEM parameters
# "" if single-end reads "--paired-end" if paired-end reads
readsType: '--paired-end'
# "--no-bam-output" if do not want transcript bam files results/enrichrwise use ""
transcriptBam: '--no-bam-output'
# "" if do not want genome bam files results/enrichrwise use "--output-genome-bam" (transcriptBam needs to be '')
genomeBam: ''
# "" if do not want star genome bam results/enrichrwise use "--star-output-genome-bam"
starGenomeBam: ''
# "" if do not want to sort bam files results/enrichrwise use "--sort-bam-by-coordinate"
sortBam: ''


# 3. samples list
# The name of the list is called "samples", each sample ID is a key containing a value, which is the path to the fastq file (two values are mapped to a key if paired-end reads)
#
# for example, for single-end reads
# samples:
#   sample1: fastq/sample1.fastq.gz
#   sample2: fastq/sample2.fastq.gz
#
# for paired-end reads
# samples:
#   sample1:
#   - /data/remote/nfs01/d02/proof/asthma/fastq/sample1_1.fastq.gz
#   - /data/remote/nfs01/d02/proof/asthma/fastq/sample1_2.fastq.gz
#   sample2:
#   - /data/remote/nfs01/d02/proof/asthma/fastq/sample2_1.fastq.gz
#   - /data/remote/nfs01/d02/proof/asthma/fastq/sample2_2.fastq.gz
#
# use the list below as an example

samples:
  HI.1141.006.Index_10.56:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_10.56_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_10.56_R2.fastq.gz
  HI.1141.006.Index_3.51:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_3.51_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_3.51_R2.fastq.gz
  HI.1141.006.Index_5.52:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_5.52_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_5.52_R2.fastq.gz
  HI.1141.006.Index_6.53:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_6.53_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_6.53_R2.fastq.gz
  HI.1141.006.Index_7.54:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_7.54_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_7.54_R2.fastq.gz
  HI.1141.006.Index_9.55:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_9.55_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1141.006.Index_9.55_R2.fastq.gz
  HI.1153.001.Index_19.61:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_19.61_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_19.61_R2.fastq.gz
  HI.1153.001.Index_22.62:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_22.62_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_22.62_R2.fastq.gz
  HI.1153.001.Index_23.63:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_23.63_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_23.63_R2.fastq.gz
  HI.1153.001.Index_25.64:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_25.64_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.001.Index_25.64_R2.fastq.gz
  HI.1153.002.Index_10.72:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_10.72_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_10.72_R2.fastq.gz
  HI.1153.002.Index_1.65:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_1.65_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_1.65_R2.fastq.gz
  HI.1153.002.Index_2.66:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_2.66_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_2.66_R2.fastq.gz
  HI.1153.002.Index_3.67:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_3.67_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_3.67_R2.fastq.gz
  HI.1153.002.Index_5.68:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_5.68_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_5.68_R2.fastq.gz
  HI.1153.002.Index_6.69:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_6.69_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_6.69_R2.fastq.gz
  HI.1153.002.Index_7.70:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_7.70_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_7.70_R2.fastq.gz
  HI.1153.002.Index_9.71:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_9.71_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.002.Index_9.71_R2.fastq.gz
  HI.1153.003.Index_13.73:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_13.73_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_13.73_R2.fastq.gz
  HI.1153.003.Index_15.74:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_15.74_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_15.74_R2.fastq.gz
  HI.1153.003.Index_16.75:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_16.75_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_16.75_R2.fastq.gz
  HI.1153.003.Index_18.76:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_18.76_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_18.76_R2.fastq.gz
  HI.1153.003.Index_23.79:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_23.79_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_23.79_R2.fastq.gz
  HI.1153.003.Index_25.80:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_25.80_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.003.Index_25.80_R2.fastq.gz
  HI.1153.004.Index_1.81:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_1.81_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_1.81_R2.fastq.gz
  HI.1153.004.Index_2.82:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_2.82_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_2.82_R2.fastq.gz
  HI.1153.004.Index_3.83:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_3.83_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_3.83_R2.fastq.gz
  HI.1153.004.Index_5.84:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_5.84_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_5.84_R2.fastq.gz
  HI.1153.004.Index_6.85:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_6.85_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_6.85_R2.fastq.gz
  HI.1153.004.Index_7.86:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_7.86_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.004.Index_7.86_R2.fastq.gz
  HI.1153.005.Index_13.89:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_13.89_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_13.89_R2.fastq.gz
  HI.1153.005.Index_15.90:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_15.90_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_15.90_R2.fastq.gz
  HI.1153.005.Index_19.93:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_19.93_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_19.93_R2.fastq.gz
  HI.1153.005.Index_22.94:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_22.94_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.005.Index_22.94_R2.fastq.gz
  HI.1153.006.Index_10.8:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_10.8_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_10.8_R2.fastq.gz
  HI.1153.006.Index_1.1:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_1.1_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_1.1_R2.fastq.gz
  HI.1153.006.Index_2.2:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_2.2_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_2.2_R2.fastq.gz
  HI.1153.006.Index_3.3:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_3.3_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_3.3_R2.fastq.gz
  HI.1153.006.Index_5.4:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_5.4_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_5.4_R2.fastq.gz
  HI.1153.006.Index_9.7:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_9.7_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.006.Index_9.7_R2.fastq.gz
  HI.1153.007.Index_13.9:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_13.9_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_13.9_R2.fastq.gz
  HI.1153.007.Index_15.10:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_15.10_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_15.10_R2.fastq.gz
  HI.1153.007.Index_16.11:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_16.11_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_16.11_R2.fastq.gz
  HI.1153.007.Index_18.12:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_18.12_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_18.12_R2.fastq.gz
  HI.1153.007.Index_19.13:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_19.13_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_19.13_R2.fastq.gz
  HI.1153.007.Index_22.14:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_22.14_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_22.14_R2.fastq.gz
  HI.1153.007.Index_23.15:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_23.15_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_23.15_R2.fastq.gz
  HI.1153.007.Index_25.16:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_25.16_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.007.Index_25.16_R2.fastq.gz
  HI.1153.008.Index_1.17:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_1.17_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_1.17_R2.fastq.gz
  HI.1153.008.Index_2.18:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_2.18_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_2.18_R2.fastq.gz
  HI.1153.008.Index_3.19:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_3.19_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_3.19_R2.fastq.gz
  HI.1153.008.Index_5.20:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_5.20_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_5.20_R2.fastq.gz
  HI.1153.008.Index_6.21:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_6.21_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_6.21_R2.fastq.gz
  HI.1153.008.Index_7.22:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_7.22_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1153.008.Index_7.22_R2.fastq.gz
  HI.1157.001.Index_16.27:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_16.27_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_16.27_R2.fastq.gz
  HI.1157.001.Index_18.28:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_18.28_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_18.28_R2.fastq.gz
  HI.1157.001.Index_19.29:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_19.29_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_19.29_R2.fastq.gz
  HI.1157.001.Index_22.30:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_22.30_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_22.30_R2.fastq.gz
  HI.1157.001.Index_23.31:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_23.31_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_23.31_R2.fastq.gz
  HI.1157.001.Index_25.32:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_25.32_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.001.Index_25.32_R2.fastq.gz
  HI.1157.002.Index_10.40:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_10.40_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_10.40_R2.fastq.gz
  HI.1157.002.Index_1.33:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_1.33_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_1.33_R2.fastq.gz
  HI.1157.002.Index_2.34:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_2.34_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_2.34_R2.fastq.gz
  HI.1157.002.Index_3.35:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_3.35_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_3.35_R2.fastq.gz
  HI.1157.002.Index_5.36:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_5.36_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_5.36_R2.fastq.gz
  HI.1157.002.Index_6.37:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_6.37_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_6.37_R2.fastq.gz
  HI.1157.002.Index_7.38:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_7.38_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_7.38_R2.fastq.gz
  HI.1157.002.Index_9.39:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_9.39_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.002.Index_9.39_R2.fastq.gz
  HI.1157.003.Index_19.45:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_19.45_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_19.45_R2.fastq.gz
  HI.1157.003.Index_22.46:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_22.46_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_22.46_R2.fastq.gz
  HI.1157.003.Index_23.47:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_23.47_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_23.47_R2.fastq.gz
  HI.1157.003.Index_25.48:
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_25.48_R1.fastq.gz
  - /data/remote/nfs01/d02/proof/asthma/fastq/HI.1157.003.Index_25.48_R2.fastq.gz


